@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZpbmlfdGVzdGVAdGVzdGUuY29tIiwiaWQiOiI2ODEzODJiMzE5OWQyNTY0NDQyMDE1YzAiLCJ1c2VybmFtZSI6InZpbmlfdGVzdGUiLCJ2YWxpZGF0aW9uX2hhc2giOiI0NDYzZDIwZTk2NDc5OWE2OTVmNjY1NjAwYzY3YTI5ZSJ9.wKIITnvWnPElgSBXGPKDviyNdhw1mgpGMx5KqT4gtUo


###
# @name log

post {{host}}/log
Content-Type: application/json
apiKey: {{apiKey}}
Authorization: Bearer {{token}}

{
    "event_id": 1,
    "mercado_produto_id": 3
}