@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZpbmlAdGVzdGUuY29tIiwiaWQiOjYsInVzZXJuYW1lIjoidmluaSIsInZhbGlkYXRpb25faGFzaCI6IjQ0NjNkMjBlOTY0Nzk5YTY5NWY2NjU2MDBjNjdhMjllIn0.4JoxiXEkeup4nSlvDt2udxVpNSQ1u_kTOAVx8FLwlY4

###
# @name log

post {{host}}/log
Content-Type: application/json
apiKey: {{apiKey}}
Authorization: Bearer {{token}}

{
    "event_id": 1
}